name: dawn-phase1
version: 0.1.0.0
github: "scottjmaddox/dawn-phase1"
license-file:
  - "LICENSE"
license: "MPL-2.0"
author: "Scott J Maddox"
maintainer: "scottjmaddox@gmail.com"
copyright: "2021 Scott J Maddox"

extra-source-files:
  - README.md

description: Please see the README on GitHub at <https://github.com/scottjmaddox/dawn-phase1#readme>

dependencies:
  - base >= 4.7 && < 5
  - either
  - containers
  - mtl
  - parsec

library:
  source-dirs: src

executables:
  dawni:
    main: dawni.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - dawn-phase1
      - haskeline
  
  enumerate-exprs:
    main: enumerate-exprs.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - dawn-phase1
  
  enumerate-non-typeable-exprs:
    main: enumerate-non-typeable-exprs.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - dawn-phase1
  
  enumerate-grouping-unstable-types:
    main: enumerate-grouping-unstable-types.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - dawn-phase1
  
  enumerate-eval-unstable-types:
    main: enumerate-eval-unstable-types.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - dawn-phase1

tests:
  dawn-phase1-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - dawn-phase1
      - hspec
